plugins:
  - ./bundles/@yarnpkg/plugin-workspace-since.js
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
